const F1Data = {
    drivers: [
    {
        "id": 1,
        "number": 44,
        "name": "Льюис Хэмилтон",
        "team": "Ferrari",
        "nationality": "Великобритания",
        "points": 156,
        "wins": 0,
        "podiums": 0,
        "championships": 7,
        championshipYears: [2008, 2014, 2015, 2017, 2018, 2019, 2020],
        "birthDate": "1985-01-07",
        "teamColor": "#DC0000",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png"
    },
    {
        "id": 2,
        "number": 63,
        "name": "Джордж Расселл",
        "team": "Mercedes",
        "nationality": "Великобритания",
        "points": 319,
        "wins": 2,
        "podiums": 9,
        "championships": 0,
        "birthDate": "1998-02-15",
        "teamColor": "#00D2BE",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png"
    },
    {
        "id": 3,
        "number": 16,
        "name": "Шарль Леклер",
        "team": "Ferrari",
        "nationality": "Монако",
        "points": 242,
        "wins": 0,
        "podiums": 7,
        "championships": 0,
        "birthDate": "1997-10-16",
        "teamColor": "#DC0000",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png"
    },
    {
        "id": 4,
        "number": 55,
        "name": "Карлос Сайнс",
        "team": "Williams",
        "nationality": "Испания",
        "points": 64,
        "wins": 0,
        "podiums": 2,
        "championships": 0,
        "birthDate": "1994-09-01",
        "teamColor": "#005AFF",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png"
    },
    {
        "id": 5,
        "number": 1,
        "name": "Макс Ферстаппен",
        "team": "Red Bull Racing",
        "nationality": "Нидерланды",
        "points": 421,
        "wins": 8,
        "podiums": 15,
        "championships": 4,
        championshipYears: [2021, 2022, 2023, 2024],
        "birthDate": "1997-09-30",
        "teamColor": "#0600EF",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png"
    },
    {
        "id": 6,
        "number": 4,
        "name": "Ландо Норрис",
        "team": "McLaren",
        "nationality": "Великобритания",
        "points": 423,
        "wins": 7,
        "podiums": 18,
        "championships": 1,
        championshipYears: [2025],
        "birthDate": "1999-11-13",
        "teamColor": "#FF8700",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png"
    },
    {
        "id": 7,
        "number": 81,
        "name": "Оскар Пиастри",
        "team": "McLaren",
        "nationality": "Австралия",
        "points": 410,
        "wins": 7,
        "podiums": 16,
        "championships": 0,
        "birthDate": "2001-04-06",
        "teamColor": "#FF8700",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/O/OSCPIA01_Oscar_Piastri/oscpia01.png"
    },
    {
        "id": 8,
        "number": 14,
        "name": "Фернандо Алонсо",
        "team": "Aston Martin",
        "nationality": "Испания",
        "points": 56,
        "wins": 0,
        "podiums": 0,
        "championships": 2,
        championshipYears: [2005, 2006],
        "birthDate": "1981-07-29",
        "teamColor": "#006F62",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png"
    },
    {
        "id": 9,
        "number": 18,
        "name": "Лэнс Стролл",
        "team": "Aston Martin",
        "nationality": "Канада",
        "points": 33,
        "wins": 0,
        "podiums": 0,
        "championships": 0,
        "birthDate": "1998-10-29",
        "teamColor": "#006F62",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png"
    },
    {
        "id": 10,
        "number": 12,
        "name": "Андреа Кими Антонелли",
        "team": "Mercedes",
        "nationality": "Италия",
        "points": 150,
        "wins": 0,
        "podiums": 3,
        "championships": 0,
        "birthDate": "2006-08-25",
        "teamColor": "#00D2BE",
        "image": "https://img2.51gt3.com/rac/racer/202503/bcca7f61b6684e26bb28aedaf8d97c53.png"
    },
    {
        "id": 11,
        "number": 87,
        "name": "Оливер Бирман",
        "team": "Haas",
        "nationality": "Великобритания",
        "points": 41,
        "wins": 0,
        "podiums": 0,
        "championships": 0,
        "birthDate": "2005-04-08",
        "teamColor": "#787878",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/O/OLIBEA01_Oliver_Bearman/olibea01.png"
    },
    {
        "id": 12,
        "number": 31,
        "name": "Эстебан Окон",
        "team": "Haas",
        "nationality": "Франция",
        "points": 38,
        "wins": 0,
        "podiums": 0,
        "championships": 0,
        "birthDate": "1996-09-17",
        "teamColor": "#787878",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png"
    },
    {
        "id": 13,
        "number": 27,
        "name": "Нико Хюлькенберг",
        "team": "Stake",
        "nationality": "Германия",
        "points": 51,
        "wins": 0,
        "podiums": 1,
        "championships": 0,
        "birthDate": "1987-08-19",
        "teamColor": "#52E252",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/N/NICHUL01_Nico_Hulkenberg/nichul01.png"
    },
    {
        "id": 14,
        "number": 5,
        "name": "Габриэль Бортолето",
        "team": "Stake",
        "nationality": "Бразилия",
        "points": 19,
        "wins": 0,
        "podiums": 0,
        "championships": 0,
        "birthDate": "2004-10-14",
        "teamColor": "#52E252",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/G/GABBOR01_Gabriel_Bortoleto/gabbor01.png"
    },
    {
        "id": 15,
        "number": 23,
        "name": "Александр Албон",
        "team": "Williams",
        "nationality": "Таиланд",
        "points": 73,
        "wins": 0,
        "podiums": 0,
        "championships": 0,
        "birthDate": "1996-03-23",
        "teamColor": "#005AFF",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/A/ALEALB01_Alexander_Albon/alealb01.png"
    },
    {
        "id": 16,
        "number": 22,
        "name": "Юки Цунода",
        "team": "Red Bull Racing",
        "nationality": "Япония",
        "points": 33,
        "wins": 0,
        "podiums": 0,
        "championships": 0,
        "birthDate": "2000-05-11",
        "teamColor": "#0600EF",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png"
    },
    {
        "id": 17,
        "number": 30,
        "name": "Лиам Лоусон",
        "team": "RB",
        "nationality": "Новая Зеландия",
        "points": 38,
        "wins": 0,
        "podiums": 0,
        "championships": 0,
        "birthDate": "2002-02-11",
        "teamColor": "#2B4562",
        "image": "https://f1flow.ru/upload/iblock/331/xhe7n29m22w12pmply3itky1ps819f4f.png"
    },
    {
        "id": 18,
        "number": 6,
        "name": "Исаак Хаджар",
        "team": "RB",
        "nationality": "Франция",
        "points": 51,
        "wins": 0,
        "podiums": 0,
        "championships": 0,
        "birthDate": "2004-09-02",
        "teamColor": "#2B4562",
        "image": "https://www.f1-world.ru/newsimg/2025/08291310.jpg"
    },
    {
        "id": 19,
        "number": 10,
        "name": "Пьер Гасли",
        "team": "Alpine",
        "nationality": "Франция",
        "points": 22,
        "wins": 0,
        "podiums": 0,
        "championships": 0,
        "birthDate": "1996-02-07",
        "teamColor": "#0090FF",
        "image": "https://media.formula1.com/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png"
    },
    {
        "id": 20,
        "number": 43,
        "name": "Франко Колапинто",
        "team": "Alpine",
        "nationality": "Аргентина",
        "points": 0,
        "wins": 0,
        "podiums": 0,
        "championships": 0,
        "birthDate": "2003-01-07",
        "teamColor": "#0090FF",
        "image": "https://f1flow.ru/upload/iblock/83a/78zwsc3cl1jtuh9xcnp68aqyhds61h76.png"
    }
    ],

    teams: [
        {
            id: 1,
            name: "Mercedes",
            fullName: "Mercedes-AMG Petronas Formula One Team",
            base: "Брекли, Великобритания",
            teamPrincipal: "Тото Вольфф",
            championships: 8,
            firstEntry: 1970,
            wins: 125,
            poles: 136,
            fastestLaps: 96,
            color: "#00D2BE",
            drivers: [10, 2],
            logo: "https://zastavki.gas-kvas.com/uploads/posts/2024-09/zastavki-gas-kvas-com-qnkw-p-zastavki-znachok-mersedes-na-telefon-3.jpg"
        },
        {
            id: 2,
            name: "Ferrari",
            fullName: "Scuderia Ferrari",
            base: "Маранелло, Италия",
            teamPrincipal: "Фредерик Вассёр",
            championships: 16,
            firstEntry: 1950,
            wins: 244,
            poles: 249,
            fastestLaps: 261,
            color: "#DC0000",
            drivers: [1, 3],
            logo: "https://i.pinimg.com/736x/48/06/4a/48064a2f06d47d827182569c0fb074e2.jpg"
        },
        {
            id: 3,
            name: "Red Bull Racing",
            fullName: "Oracle Red Bull Racing",
            base: "Милтон-Кинс, Великобритания",
            teamPrincipal: "Кристиан Хорнер",
            championships: 6,
            firstEntry: 1997,
            wins: 116,
            poles: 96,
            fastestLaps: 94,
            color: "#0600EF",
            drivers: [5, 16],
            logo: "https://i.pinimg.com/564x/51/0c/07/510c07f646e06fbda90f4eb522425e4f.jpg"
        },
        {
            id: 4,
            name: "McLaren",
            fullName: "McLaren Formula 1 Team",
            base: "Уокинг, Великобритания",
            teamPrincipal: "Андреа Стелла",
            championships: 8,
            firstEntry: 1966,
            wins: 183,
            poles: 158,
            fastestLaps: 164,
            color: "#FF8700",
            drivers: [7, 6],
            logo: "https://i.pinimg.com/736x/1b/5d/14/1b5d145a2279719a9e8239530c194406.jpg"
        },
        {
            id: 5,
            name: "Aston Martin",
            fullName: "Aston Martin Aramco Formula One Team",
            base: "Сильверстоун, Великобритания",
            teamPrincipal: "Майк Крак",
            championships: 0,
            firstEntry: 1959,
            wins: 0,
            poles: 1,
            fastestLaps: 1,
            color: "#006F62",
            drivers: [9, 8],
            logo: "https://media.formula1.com/content/dam/fom-website/2018-redesign-assets/team%20logos/aston%20martin.png"
        },
        {
            id: 6,
            name: "Alpine",
            fullName: "BWT Alpine F1 Team",
            base: "Энстоун, Великобритания",
            teamPrincipal: "Бруно Фамин",
            championships: 2,
            firstEntry: 1986,
            wins: 21,
            poles: 20,
            fastestLaps: 16,
            color: "#0090FF",
            drivers: [15, 16],
            logo: "https://media.formula1.com/content/dam/fom-website/2018-redesign-assets/team%20logos/alpine.png"
        },
        {
            id: 7,
            name: "Williams",
            fullName: "Williams Racing",
            base: "Гроув, Великобритания",
            teamPrincipal: "Джеймс Воулз",
            championships: 9,
            firstEntry: 1978,
            wins: 114,
            poles: 129,
            fastestLaps: 133,
            color: "#005AFF",
            drivers: [19, 20],
            logo: "https://media.formula1.com/content/dam/fom-website/2018-redesign-assets/team%20logos/williams.png"
        },
        {
            id: 8,
            name: "RB",
            fullName: "Visa Cash App RB Formula One Team",
            base: "Фаэнца, Италия",
            teamPrincipal: "Лоран Мекис",
            championships: 0,
            firstEntry: 1985,
            wins: 0,
            poles: 0,
            fastestLaps: 1,
            color: "#2B4562",
            drivers: [13, 14],
            logo: "https://media.formula1.com/content/dam/fom-website/2018-redesign-assets/team%20logos/alphatauri.png"
        },
        {
            id: 9,
            name: "Stake",
            fullName: "Stake F1 Team Kick Sauber",
            base: "Хинвиль, Швейцария",
            teamPrincipal: "Алессандро Алунни Брави",
            championships: 0,
            firstEntry: 1993,
            wins: 1,
            poles: 1,
            fastestLaps: 7,
            color: "#52E252",
            drivers: [17, 18],
            logo: "https://media.formula1.com/content/dam/fom-website/2018-redesign-assets/team%20logos/alfa%20romeo.png"
        },
        {
            id: 10,
            name: "Haas",
            fullName: "MoneyGram Haas F1 Team",
            base: "Каннаполис, США",
            teamPrincipal: "Аяо Комацу",
            championships: 0,
            firstEntry: 2016,
            wins: 0,
            poles: 1,
            fastestLaps: 2,
            color: "#787878",
            drivers: [11, 12],
            logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXlPmf9THPYuMjAuuLI4EL6LOhb8nFWqifYg&s"
        }
    ],

    calendar: [
        {
            id: 1,
            name: "Бахрейн",
            circuit: "Международный автодром Бахрейна",
            location: "Сахир, Бахрейн",
            date: "2024-03-02",
            laps: 57,
            circuitLength: 5.412,
            raceDistance: 308.238,
            lapRecord: "Педро де ла Роса - 1:31.447 (2005)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Bahrain_Circuit.png"
        },
        {
            id: 2,
            name: "Саудовская Аравия",
            circuit: "Городская трасса Джидды",
            location: "Джидда, Саудовская Аравия",
            date: "2024-03-09",
            laps: 50,
            circuitLength: 6.174,
            raceDistance: 308.450,
            lapRecord: "Льюис Хэмилтон - 1:30.734 (2021)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Saudi_Arabia_Circuit.png"
        },
        {
            id: 3,
            name: "Австралия",
            circuit: "Альберт-Парк",
            location: "Мельбурн, Австралия",
            date: "2024-03-24",
            laps: 58,
            circuitLength: 5.278,
            raceDistance: 306.124,
            lapRecord: "Шарль Леклер - 1:20.260 (2022)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Australia_Circuit.png"
        },
        {
            id: 4,
            name: "Япония",
            circuit: "Судзука",
            location: "Судзука, Япония",
            date: "2024-04-07",
            laps: 53,
            circuitLength: 5.807,
            raceDistance: 307.471,
            lapRecord: "Льюис Хэмилтон - 1:30.983 (2019)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Japan_Circuit.png"
        },
        {
            id: 5,
            name: "Китай",
            circuit: "Шанхай",
            location: "Шанхай, Китай",
            date: "2024-04-21",
            laps: 56,
            circuitLength: 5.451,
            raceDistance: 305.066,
            lapRecord: "Михаэль Шумахер - 1:32.238 (2004)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/China_Circuit.png"
        },
        {
            id: 6,
            name: "Майами",
            circuit: "Майами Интернешнл Автодром",
            location: "Майами, США",
            date: "2024-05-05",
            laps: 57,
            circuitLength: 5.412,
            raceDistance: 308.326,
            lapRecord: "Макс Ферстаппен - 1:29.708 (2023)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Miami_Circuit.png"
        },
        {
            id: 7,
            name: "Италия (Эмилия-Романья)",
            circuit: "Имола",
            location: "Имола, Италия",
            date: "2024-05-19",
            laps: 63,
            circuitLength: 4.909,
            raceDistance: 309.049,
            lapRecord: "Льюис Хэмилтон - 1:15.484 (2020)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Emilia_Romagna_Circuit.png"
        },
        {
            id: 8,
            name: "Монако",
            circuit: "Монте-Карло",
            location: "Монте-Карло, Монако",
            date: "2024-05-26",
            laps: 78,
            circuitLength: 3.337,
            raceDistance: 260.286,
            lapRecord: "Льюис Хэмилтон - 1:12.909 (2021)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Monaco_Circuit.png"
        },
        {
            id: 9,
            name: "Канада",
            circuit: "Жиль Вильнёв",
            location: "Монреаль, Канада",
            date: "2024-06-09",
            laps: 70,
            circuitLength: 4.361,
            raceDistance: 305.270,
            lapRecord: "Валттери Боттас - 1:13.078 (2019)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Canada_Circuit.png"
        },
        {
            id: 10,
            name: "Испания",
            circuit: "Барселона-Каталунья",
            location: "Барселона, Испания",
            date: "2024-06-23",
            laps: 66,
            circuitLength: 4.675,
            raceDistance: 308.424,
            lapRecord: "Макс Ферстаппен - 1:16.330 (2023)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Spain_Circuit.png"
        },
        {
            id: 11,
            name: "Австрия",
            circuit: "Ред Булл Ринг",
            location: "Шпильберг, Австрия",
            date: "2024-06-30",
            laps: 71,
            circuitLength: 4.318,
            raceDistance: 306.452,
            lapRecord: "Карлос Сайнс - 1:05.619 (2020)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Austria_Circuit.png"
        },
        {
            id: 12,
            name: "Великобритания",
            circuit: "Сильверстоун",
            location: "Сильверстоун, Великобритания",
            date: "2024-07-07",
            laps: 52,
            circuitLength: 5.891,
            raceDistance: 306.198,
            lapRecord: "Макс Ферстаппен - 1:27.097 (2020)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Great_Britain_Circuit.png"
        },
        {
            id: 13,
            name: "Венгрия",
            circuit: "Хунгароринг",
            location: "Будапешт, Венгрия",
            date: "2024-07-21",
            laps: 70,
            circuitLength: 4.381,
            raceDistance: 306.630,
            lapRecord: "Льюис Хэмилтон - 1:16.627 (2020)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Hungary_Circuit.png"
        },
        {
            id: 14,
            name: "Бельгия",
            circuit: "Спа-Франкоршам",
            location: "Спа, Бельгия",
            date: "2024-07-28",
            laps: 44,
            circuitLength: 7.004,
            raceDistance: 308.052,
            lapRecord: "Валттери Боттас - 1:46.286 (2018)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Belgium_Circuit.png"
        },
        {
            id: 15,
            name: "Нидерланды",
            circuit: "Зандворт",
            location: "Зандворт, Нидерланды",
            date: "2024-08-25",
            laps: 72,
            circuitLength: 4.259,
            raceDistance: 306.648,
            lapRecord: "Льюис Хэмилтон - 1:11.097 (2021)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Netherlands_Circuit.png"
        },
        {
            id: 16,
            name: "Италия",
            circuit: "Монца",
            location: "Монца, Италия",
            date: "2024-09-01",
            laps: 53,
            circuitLength: 5.793,
            raceDistance: 306.720,
            lapRecord: "Рубенс Баррикелло - 1:21.046 (2004)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Italy_Circuit.png"
        },
        {
            id: 17,
            name: "Азербайджан",
            circuit: "Баку",
            location: "Баку, Азербайджан",
            date: "2024-09-15",
            laps: 51,
            circuitLength: 6.003,
            raceDistance: 306.049,
            lapRecord: "Шарль Леклер - 1:43.009 (2019)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Netherlands_Circuit.png"
        },
        {
            id: 18,
            name: "Сингапур",
            circuit: "Марина Бэй",
            location: "Сингапур",
            date: "2024-09-22",
            laps: 61,
            circuitLength: 5.063,
            raceDistance: 308.706,
            lapRecord: "Льюис Хэмилтон - 1:41.905 (2023)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Singapore_Circuit.png"
        },
        {
            id: 19,
            name: "США",
            circuit: "Трасса Америк",
            location: "Остин, США",
            date: "2024-10-20",
            laps: 56,
            circuitLength: 5.513,
            raceDistance: 308.405,
            lapRecord: "Шарль Леклер - 1:36.169 (2019)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Hungary_Circuit.png"
        },
        {
            id: 20,
            name: "Мексика",
            circuit: "Аутодромо Эрманос Родригес",
            location: "Мехико, Мексика",
            date: "2024-10-27",
            laps: 71,
            circuitLength: 4.304,
            raceDistance: 305.354,
            lapRecord: "Валттери Боттас - 1:17.774 (2021)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Mexico_Circuit.png"
        },
        {
            id: 21,
            name: "Бразилия",
            circuit: "Интерлагос",
            location: "Сан-Паулу, Бразилия",
            date: "2024-11-03",
            laps: 71,
            circuitLength: 4.309,
            raceDistance: 305.909,
            lapRecord: "Валттери Боттас - 1:10.540 (2018)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Brazil_Circuit.png"
        },
        {
            id: 22,
            name: "Лас-Вегас",
            circuit: "Стрип Лас-Вегаса",
            location: "Лас-Вегас, США",
            date: "2024-11-23",
            laps: 50,
            circuitLength: 6.201,
            raceDistance: 309.950,
            lapRecord: "Оскар Пиастри - 1:35.490 (2023)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Las_Vegas_Circuit.png"
        },
        {
            id: 23,
            name: "Катар",
            circuit: "Лусаил",
            location: "Лусаил, Катар",
            date: "2024-12-01",
            laps: 57,
            circuitLength: 5.380,
            raceDistance: 306.660,
            lapRecord: "Макс Ферстаппен - 1:24.319 (2023)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Qatar_Circuit.png"
        },
        {
            id: 24,
            name: "Абу-Даби",
            circuit: "Яс Марина",
            location: "Абу-Даби, ОАЭ",
            date: "2024-12-08",
            laps: 58,
            circuitLength: 5.281,
            raceDistance: 306.183,
            lapRecord: "Макс Ферстаппен - 1:26.103 (2021)",
            image: "https://media.formula1.com/image/upload/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Abu_Dhabi_Circuit.png"
        }
    ],

    news: [
        {
            id: 1,
            title: "Новый контракт Хэмилтона с Ferrari",
            date: "2025-02-01",
            summary: "Льюис Хэмилтон подписал контракт с Ferrari на сезоны 2025-2026.",
            category: "Трансферы",
            image: "https://www.idman.biz/media/2025/10/19/1920x1280/f1-hamilton-ferrari.jpg?v=1760824182"
        },
        {
            id: 2,
            title: "Рекорд Ферстаппена",
            date: "2025-03-15",
            summary: "Макс Ферстаппен установил новый рекорд по количеству побед подряд.",
            category: "Рекорды",
            image: "https://sportnews.kz/static/n/m3wuvgjw5lc48su1pyorg.webp"
        },
        {
            id: 3,
            title: "Новые правила 2026",
            date: "2025-01-20",
            summary: "FIA представила новые технические регламенты для сезона 2026.",
            category: "Регламент",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWu66yGWIQv1pw0sKKLCGtum46z8zidpFK_w&s"
        },
        {
            id: 4,
            title: "Возвращение Гран-при Китая",
            date: "2025-03-10",
            summary: "После четырехлетнего перерыва Гран-при Китая возвращается в календарь.",
            category: "Календарь",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1V5E29oLvnITRAlaWloOAG8Ebprc60FXdig&s"
        }
    ],

    videos: [
        {
            id: 1,
            title: "Лучшие обгоны сезона 2023",
            duration: "4:32",
            views: "2.3M",
            date: "2023-12-20",
            thumbnail: "https://img.championat.com/s/520x346/news/big/l/w/drs-chush-kotoraya-portit-formulu-1_16484143721199828253.jpg",
            url: "https://youtu.be/5gm-a9O7D78?si=7VzBQhJFnEvJS_lL"
        },
        {
            id: 2,
            title: "Как устроен болид F1",
            duration: "8:15",
            views: "1.8M",
            date: "2024-01-15",
            thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpPa7LVOZwzIAo9uziSfGCpgOGKBTXmH9JvQ&s",
            url: "https://youtu.be/5gm-a9O7D78?si=7VzBQhJFnEvJS_lL"
        },
        {
            id: 3,
            title: "Топ-10 крахов в истории F1",
            duration: "10:42",
            views: "3.1M",
            date: "2023-11-05",
            thumbnail: "https://resizer.mail.ru/p/0b8d0cf8-3e33-59d3-9ecd-72a16c3319f7/AQAGlP55svMCdqxyw8ZJMD6oP9cn5BbmpvVARoH9zgcFSG9MarIL6QX1XnXMQLT7SfMzvDt1KiaBkz72Az_Cd3HMF-M.jpg",
            url: "https://youtu.be/5gm-a9O7D78?si=7VzBQhJFnEvJS_lL"
        },
        {
            id: 4,
            title: "Подготовка к Гран-при Монако",
            duration: "6:23",
            views: "1.2M",
            date: "2024-05-01",
            thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkNkSM6AfIUN_ClE5Zk5E_kJvYKgAGnnDtsQ&s",
            url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        }
    ]
};
if (typeof module !== 'undefined' && module.exports) {
    module.exports = F1Data;
}